### ISSUE TITLE
Compile failure w/ pre-AMP `base` versions

### ISSUE THREAD

**Issue by hvr** [icidasset/shikensu#1]
Hi,

I noticed on http://104.239.175.197:8080/package/shikensu  that recent releases fail to compile with pre-AMP `base` versions, e.g. w/ GHC 7.8.4:

```
Configuring component lib from shikensu-0.3.0...
Preprocessing library shikensu-0.3.0...
[1 of 8] Compiling Shikensu.Types   ( src/Shikensu/Types.hs, /tmp/matrix-worker/1491048278/dist-newstyle/build/x86_64-linux/ghc-7.8.4/shikensu-0.3.0/build/Shikensu/Types.o )
[2 of 8] Compiling Shikensu.Metadata ( src/Shikensu/Metadata.hs, /tmp/matrix-worker/1491048278/dist-newstyle/build/x86_64-linux/ghc-7.8.4/shikensu-0.3.0/build/Shikensu/Metadata.o )
[3 of 8] Compiling Shikensu.Utilities ( src/Shikensu/Utilities.hs, /tmp/matrix-worker/1491048278/dist-newstyle/build/x86_64-linux/ghc-7.8.4/shikensu-0.3.0/build/Shikensu/Utilities.o )

src/Shikensu/Utilities.hs:62:16:
    Could not deduce (Functor m) arising from a use of ‘fmap’
    from the context (Monad m)
      bound by the type signature for
                 lsequence :: Monad m => [(String, m a)] -> m [(String, a)]
      at src/Shikensu/Utilities.hs:48:14-62
    Possible fix:
      add (Functor m) to the context of
        the type signature for
          lsequence :: Monad m => [(String, m a)] -> m [(String, a)]
    In the second argument of ‘(|>)’, namely ‘fmap (zip identifiers)’
    In the expression:
      dictionaries |> sequence |> fmap (zip identifiers)
    In the expression:
      let
        unzippedList = unzip list
        identifiers = fst unzippedList
        dictionaries = snd unzippedList
      in dictionaries |> sequence |> fmap (zip identifiers)
```

If you don't want to support `base-4.7` and older, the simplest way to address is to advertise the supported version range more accurately by tightening the lower bound on `base` to e.g. `base >= 4.8`. This way `cabal` won't run into compile failures.

**Comment by icidasset** [comment]
Thanks!! Will adjust the version range ☺️

**Comment by icidasset** [comment]
Upload `0.3.1` with the new `base` version constraint.

**Comment by hvr** [comment]
Great! Fyi, I went ahead and revised the meta-data for the 3 affected releases (which btw is something you can do yourself as well at e.g.  https://hackage.haskell.org/package/shikensu-0.3.2/shikensu.cabal/edit):

 - https://hackage.haskell.org/package/shikensu-0.3.0/revisions/
 - https://hackage.haskell.org/package/shikensu-0.2.1/revisions/
 - https://hackage.haskell.org/package/shikensu-0.2.0/revisions/

**Comment by icidasset** [comment]
Thanks! 🙏  Good to know.
